(SELECT LEFT(SALES_DATE, 10), 
        PRODUCT_ID, 
        USER_ID, 
        SALES_AMOUNT
 FROM ONLINE_SALE
 WHERE MONTH(SALES_DATE) = 3)
UNION
(SELECT LEFT(SALES_DATE, 10),
        PRODUCT_ID, 
        NULL USER_ID, 
        SALES_AMOUNT
 FROM OFFLINE_SALE
 WHERE MONTH(SALES_DATE) = 3)
ORDER BY 1, 2, 3