SELECT MEM.MEMBER_NAME,
       REV.REVIEW_TEXT,
       DATE_FORMAT(REV.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW REV
JOIN MEMBER_PROFILE MEM ON REV.MEMBER_ID = MEM.MEMBER_ID
WHERE MEM.MEMBER_ID = (SELECT MEMBER_ID
                   FROM REST_REVIEW
                   GROUP BY 1
                   ORDER BY COUNT(REVIEW_ID) DESC
                   LIMIT 1)
ORDER BY 3, 2