WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) IN ('8', '9', '10')
    GROUP BY 1
    HAVING COUNT(*) >= 5
)
SELECT 
    MONTH(START_DATE) MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) IN ('8', '9', '10')
    AND CAR_ID IN (SELECT CAR_ID FROM A)
GROUP BY 1, 2
HAVING RECORDS > 0
ORDER BY 1, 2 DESC