SELECT NAME, DATETIME
FROM (
        SELECT I.NAME, I.DATETIME, DATEDIFF(I.DATETIME, O.DATETIME)
        FROM ANIMAL_INS I
        LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE O.DATETIME IS NULL
        ORDER BY 3 DESC
    ) A
ORDER BY 2
LIMIT 3