SELECT INFO.REST_ID, 
       INFO.REST_NAME, 
       INFO.FOOD_TYPE, 
       INFO.FAVORITES, 
       INFO.ADDRESS, 
       ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_INFO INFO
JOIN REST_REVIEW REV ON INFO.REST_ID = REV.REST_ID
GROUP BY REST_ID
HAVING INFO.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC