WITH VAL AS (SELECT
    I.ANIMAL_ID,
    I.NAME,
    DATEDIFF(O.DATETIME, I.DATETIME)
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY 3 DESC)

SELECT ANIMAL_ID, NAME
FROM VAL
LIMIT 2